context:
  version: "0.3.0"

package:
  name: jupyter-ai-acp-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-acp-client/jupyter_ai_acp_client-${{ version }}.tar.gz
  sha256: 8b60f94411a7cb92606a7283fea9aaf1bf2bfdb0025a9424ce477928176231bc

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
  run:
    - python >=${{ python_min }}
    - agent-client-protocol >=0.11.0,<0.12.0
    - jupyter-ai-persona-manager >=0.2.0
    - jupyter_server >=2.4.0,<3
    - jupyterlab-chat >=0.25.0
    - pydantic >=2,<3

tests:
  - python:
      imports:
        - jupyter_ai_acp_client
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-acp-client
  summary: "The ACP client implementation in Jupyter AI"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-acp-client

extra:
  recipe-maintainers:
    - jtpio
    - dlqqq
    - andrii-i
    - conda-forge/jupyter-ai
